export const RANKED_QUEUE_ID = '1'
export const VANILLA_QUEUE_ID = '2'
export const SANDBOX_QUEUE_ID = '3'
export const SMALLWORLD_QUEUE_ID = '4'
export const CASUAL_QUEUE_ID = '5'
export const CDN_URL = 'https://balatromp.b-cdn.net'
