export interface JokerInfo {
  name: string
  file: string
}

export const jokers: { [key: string]: JokerInfo } = {
  j_8_ball: { name: '8 Ball', file: 'j_8_ball.png' },
  j_abstract: { name: 'Abstract Joker', file: 'j_abstract.png' },
  j_acrobat: { name: 'Acrobat', file: 'j_acrobat.png' },
  j_ancient: { name: 'Ancient Joker', file: 'j_ancient.png' },
  j_arrowhead: { name: 'Arrowhead', file: 'j_arrowhead.png' },
  j_astronomer: { name: 'Astronomer', file: 'j_astronomer.png' },
  j_banner: { name: 'Banner', file: 'j_banner.png' },
  j_baron: { name: 'Baron', file: 'j_baron.png' },
  j_baseball: { name: 'Baseball Card', file: 'j_baseball.png' },
  j_bloodstone: { name: 'Bloodstone', file: 'j_bloodstone.png' },
  j_blueprint: { name: 'Blueprint', file: 'j_blueprint.png' },
  j_bootstraps: { name: 'Bootstraps', file: 'j_bootstraps.png' },
  j_brainstorm: { name: 'Brainstorm', file: 'j_brainstorm.png' },
  j_bull: { name: 'Bull', file: 'j_bull.png' },
  j_burnt: { name: 'Burnt Joker', file: 'j_burnt.png' },
  j_business: { name: 'Business Card', file: 'j_business.png' },
  j_caino: { name: 'Caino', file: 'j_caino.png' },
  j_campfire: { name: 'Campfire', file: 'j_campfire.png' },
  j_card_sharp: { name: 'Card Sharp', file: 'j_card_sharp.png' },
  j_cartomancer: { name: 'Cartomancer', file: 'j_cartomancer.png' },
  j_castle: { name: 'Castle', file: 'j_castle.png' },
  j_ceremonial: { name: 'Ceremonial Dagger', file: 'j_ceremonial.png' },
  j_certificate: { name: 'Certificate', file: 'j_certificate.png' },
  j_chaos: { name: 'Chaos the Clown', file: 'j_chaos.png' },
  j_chicot: { name: 'Chicot', file: 'j_chicot.png' },
  j_clever: { name: 'Clever Joker', file: 'j_clever.png' },
  j_cloud_9: { name: 'Cloud 9', file: 'j_cloud_9.png' },
  j_crafty: { name: 'Crafty Joker', file: 'j_crafty.png' },
  j_crazy: { name: 'Crazy Joker', file: 'j_crazy.png' },
  j_credit_card: { name: 'Credit Card', file: 'j_credit_card.png' },
  j_delayed_grat: { name: 'Delayed Gratification', file: 'j_delayed_grat.png' },
  j_devious: { name: 'Devious Joker', file: 'j_devious.png' },
  j_diet_cola: { name: 'Diet Cola', file: 'j_diet_cola.png' },
  j_drivers_license: {
    name: "Driver's License",
    file: 'j_drivers_license.png',
  },
  j_droll: { name: 'Droll Joker', file: 'j_droll.png' },
  j_drunkard: { name: 'Drunkard', file: 'j_drunkard.png' },
  j_duo: { name: 'The Duo', file: 'j_duo.png' },
  j_dusk: { name: 'Dusk', file: 'j_dusk.png' },
  j_egg: { name: 'Cavendish', file: 'j_egg.png' },
  j_erosion: { name: 'Erosion', file: 'j_erosion.png' },
  j_even_steven: { name: 'Even Steven', file: 'j_even_steven.png' },
  j_family: { name: 'The Family', file: 'j_family.png' },
  j_fibonacci: { name: 'Fibonacci', file: 'j_fibonacci.png' },
  j_flash: { name: 'Flash Card', file: 'j_flash.png' },
  j_flower_pot: { name: 'Flower Pot', file: 'j_flower_pot.png' },
  j_fortune_teller: { name: 'Fortune Teller', file: 'j_fortune_teller.png' },
  j_four_fingers: { name: 'Four Fingers', file: 'j_four_fingers.png' },
  j_gift: { name: 'Gift Card', file: 'j_gift.png' },
  j_glass: { name: 'Glass Joker', file: 'j_glass.png' },
  j_gluttenous_joker: {
    name: 'Gluttonous Joker',
    file: 'j_gluttenous_joker.png',
  },
  j_golden: { name: 'Golden Joker', file: 'j_golden.png' },
  j_greedy_joker: { name: 'Greedy Joker', file: 'j_greedy_joker.png' },
  j_gros_michel: { name: 'Gros Michel', file: 'j_gros_michel.png' },
  j_hack: { name: 'Hack', file: 'j_hack.png' },
  j_half: { name: 'Half Joker', file: 'j_half.png' },
  j_hallucination: { name: 'Hallucination', file: 'j_hallucination.png' },
  j_hanging_chad: { name: 'Hanging Chad', file: 'j_hanging_chad.png' },
  j_hit_the_road: { name: 'Hit the Road', file: 'j_hit_the_road.png' },
  j_hologram: { name: 'Hologram', file: 'j_hologram.png' },
  j_idol: { name: 'The Idol', file: 'j_idol.png' },
  j_invisible: { name: 'Invisible Joker', file: 'j_invisible.png' },
  j_joker: { name: 'Joker', file: 'j_joker.png' },
  j_jolly: { name: 'Jolly Joker', file: 'j_jolly.png' },
  j_juggler: { name: 'Juggler', file: 'j_juggler.png' },
  j_locked: { name: 'Locked', file: 'j_locked.png' },
  j_loyalty_card: { name: 'Loyalty Card', file: 'j_loyalty_card.png' },
  j_luchador: { name: 'Luchador', file: 'j_luchador.png' },
  j_lucky_cat: { name: 'Lucky Cat', file: 'j_lucky_cat.png' },
  j_lusty_joker: { name: 'Lusty Joker', file: 'j_lusty_joker.png' },
  j_mad: { name: 'Mad Joker', file: 'j_mad.png' },
  j_madness: { name: 'Madness', file: 'j_madness.png' },
  j_mail: { name: 'Mail-In Rebate', file: 'j_mail.png' },
  j_marble: { name: 'Marble Joker', file: 'j_marble.png' },
  j_matador: { name: 'Matador', file: 'j_matador.png' },
  j_merry_andy: { name: 'Merry Andy', file: 'j_merry_andy.png' },
  j_midas_mask: { name: 'Midas Mask', file: 'j_midas_mask.png' },
  j_mime: { name: 'Mime', file: 'j_mime.png' },
  j_misprint: { name: 'Misprint', file: 'j_misprint.png' },
  j_mr_bones: { name: 'Mr. Bones', file: 'j_mr_bones.png' },
  j_mystic_summit: { name: 'Mystic Summit', file: 'j_mystic_summit.png' },
  j_obelisk: { name: 'Obelisk', file: 'j_obelisk.png' },
  j_odd_todd: { name: 'Odd Todd', file: 'j_odd_todd.png' },
  j_onyx_agate: { name: 'Onyx Agate', file: 'j_onyx_agate.png' },
  j_oops: { name: 'Oops! All 6s', file: 'j_oops.png' },
  j_order: { name: 'The Order', file: 'j_order.png' },
  j_pareidolia: { name: 'Pareidolia', file: 'j_pareidolia.png' },
  j_perkeo: { name: 'Perkeo', file: 'j_perkeo.png' },
  j_photograph: { name: 'Photograph', file: 'j_photograph.png' },
  j_popcorn: { name: 'Popcorn', file: 'j_popcorn.png' },
  j_raised_fist: { name: 'Raised Fist', file: 'j_raised_fist.png' },
  j_ramen: { name: 'Ramen', file: 'j_ramen.png' },
  j_red_card: { name: 'Red Card', file: 'j_red_card.png' },
  j_reserved_parking: {
    name: 'Reserved Parking',
    file: 'j_reserved_parking.png',
  },
  j_ride_the_bus: { name: 'Ride the Bus', file: 'j_ride_the_bus.png' },
  j_riff_raff: { name: 'Riff-raff', file: 'j_riff_raff.png' },
  j_ring_master: { name: 'Showman', file: 'j_ring_master.png' },
  j_rocket: { name: 'Rocket', file: 'j_rocket.png' },
  j_rough_gem: { name: 'Rough Gem', file: 'j_rough_gem.png' },
  j_satellite: { name: 'Satellite', file: 'j_satellite.png' },
  j_scary_face: { name: 'Scary Face', file: 'j_scary_face.png' },
  j_scholar: { name: 'Scholar', file: 'j_scholar.png' },
  j_seance: { name: 'Seance', file: 'j_seance.png' },
  j_seeing_double: { name: 'Seeing Double', file: 'j_seeing_double.png' },
  j_selzer: { name: 'Seltzer', file: 'j_selzer.png' },
  j_shoot_the_moon: { name: 'Shoot the Moon', file: 'j_shoot_the_moon.png' },
  j_shortcut: { name: 'Shortcut', file: 'j_shortcut.png' },
  j_sly: { name: 'Sly Joker', file: 'j_sly.png' },
  j_smeared: { name: 'Smeared Joker', file: 'j_smeared.png' },
  j_smiley: { name: 'Smiley Face', file: 'j_smiley.png' },
  j_sock_and_buskin: { name: 'Sock and Buskin', file: 'j_sock_and_buskin.png' },
  j_space: { name: 'Space Joker', file: 'j_space.png' },
  j_square: { name: 'Square Joker', file: 'j_square.png' },
  j_steel_joker: { name: 'Steel Joker', file: 'j_steel_joker.png' },
  j_stencil: { name: 'Joker Stencil', file: 'j_stencil.png' },
  j_stone: { name: 'Stone Joker', file: 'j_stone.png' },
  j_stuntman: { name: 'Stuntman', file: 'j_stuntman.png' },
  j_supernova: { name: 'Supernova', file: 'j_supernova.png' },
  j_swashbuckler: { name: 'Swashbuckler', file: 'j_swashbuckler.png' },
  j_throwback: { name: 'Throwback', file: 'j_throwback.png' },
  j_ticket: { name: 'Golden Ticket', file: 'j_ticket.png' },
  j_to_the_moon: { name: 'To the Moon', file: 'j_to_the_moon.png' },
  j_trading: { name: 'Trading Card', file: 'j_trading.png' },
  j_tribe: { name: 'The Tribe', file: 'j_tribe.png' },
  j_triboulet: { name: 'Triboulet', file: 'j_triboulet.png' },
  j_trio: { name: 'The Trio', file: 'j_trio.png' },
  j_troubadour: { name: 'Troubadour', file: 'j_troubadour.png' },
  j_trousers: { name: 'Spare Trousers', file: 'j_trousers.png' },
  j_turtle_bean: { name: 'Turtle Bean', file: 'j_turtle_bean.png' },
  j_undiscovered: { name: 'Locked', file: 'j_undiscovered.png' },
  j_vagabond: { name: 'Vagabond', file: 'j_vagabond.png' },
  j_vampire: { name: 'Vampire', file: 'j_vampire.png' },
  j_walkie_talkie: { name: 'Walkie Talkie', file: 'j_walkie_talkie.png' },
  j_wee: { name: 'Wee Joker', file: 'j_wee.png' },
  j_wily: { name: 'Wily Joker', file: 'j_wily.png' },
  j_wrathful_joker: { name: 'Wrathful Joker', file: 'j_wrathful_joker.png' },
  j_yorick: { name: 'Yorick', file: 'j_yorick.png' },
  j_zany: { name: 'Zany Joker', file: 'j_zany.png' },
}
